# pytorch_add_bug
Bug with the in-place add function

follow it here <https://github.com/pytorch/pytorch/issues/14463>
